### ISSUE TITLE
Managed Identity Abbreviation

### ISSUE THREAD

**Issue by kbocock-krg** [MicrosoftDocs/cloud-adoption-framework#1029]
id is too common? Shouldn't this be mi or mid?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by jamasten** [comment]
Neither of these suggestions are good examples since there are two types of managed identities.  **System-assigned identities** do not require a prefix since they are not exposed as resources at the resource group scope. **User-assigned identities** do require a prefix and are resources within the resource group scope.  Why is "id" too common?  Is there a conflict with another Azure resource? Would you prefer "uaid"? The idea around the prefixes is to use the least amount of characters possible without creating conflicts with other resources at the same scope.

**Comment by stephen-sumner** [comment]
@kbocock-krg - Thanks so much for the input! We will take this suggestion into consideration as we update our guidance
