### ISSUE TITLE
Web link not working

### ISSUE THREAD

**Issue by MaikelMartensWater** [MicrosoftDocs/cloud-adoption-framework#1039]
This link is not working in the following text:

If your migration scenario is atypical, you can get a personalized assessment of your organization's migration readiness by using the [strategic migration and readiness tool (SMART) assessment](https://learn.microsoft.com/en-us/assessments/?id=strategic-migration-assessment). Use it to identify the guidance that best aligns to your current needs.

**(https://learn.microsoft.com/en-us/assessments/?id=strategic-migration-assessment)**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 150e319d-d5c9-5e7e-a233-a4818bf53a72
* Version Independent ID: c2d8e1bd-a4ef-a979-095a-148bc2276d9e
* Content: [Get started: Accelerate migration - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/get-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Thanks you @MaikelMartensWater for letting us know!  The Microsoft Assessments platform underwent a UI and URL change, which these links didn't get updated to handle.  There were other pages in CAF with the same issue.  I've opened a PR to fix them all.  Once this issue is marked closed, you can assume within about 48 business hours, the links will be fixed.

The replacement is <https://learn.microsoft.com/assessments/Strategic-Migration-Assessment/>
