### ISSUE TITLE
Possible missing part in Scenario 4 diagram

### ISSUE THREAD

**Issue by nsaddadi** [MicrosoftDocs/cloud-adoption-framework#1046]
[Thanks for this nicely written document, although it seems that one part is missing within scenario 4  in the diagram. And it is the illustration of vWAN, as it is multiple times referred within this part. I am looking forward to getting your opinion about it. Regards Navisa Saddadi]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae25fd8-2bb8-0f5c-6f84-b2868862b37b
* Version Independent ID: 3ae25fd8-2bb8-0f5c-6f84-b2868862b37b
* Content: [Enterprise-scale example architectures connectivity to Azure VMware Solution - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/example-architectures)
* Content Source: [docs/scenarios/azure-vmware/example-architectures.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/example-architectures.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @sablair
* Microsoft Alias: **janet**

**Comment by v-fearam** [comment]
Hi @nsaddadi

Sorry for the delay. 

The document has changed a lot since the issue was reported. [The scenario was deleted](https://github.com/MicrosoftDocs/cloud-adoption-framework/commit/5408301cb813b3322a6957de9288933bcfef8007)



I will close the ticket, but feel free to open a new one if you still have concerns.
