### ISSUE TITLE
Deployment of Data Managment Landing Zone not possible in azure free acount 

### ISSUE THREAD

**Issue by pvath** [MicrosoftDocs/cloud-adoption-framework#1067]
It seems that its not possible to deploy a Data Managment Landing Zone using the template from https://github.com/Azure/data-management-zone in a free azure acount. This results in the following error 
"code": "StaticPublicIPCountLimitReached"

Is there any workaround to avoid this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dce473ea-2efc-4b56-f4b7-7582d8725137
* Version Independent ID: dce473ea-2efc-4b56-f4b7-7582d8725137
* Content: [Tutorial - Create a data landing zone - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/tutorials/tutorial-create-data-landing-zone#supported-regions)
* Content Source: [docs/scenarios/cloud-scale-analytics/tutorials/tutorial-create-data-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/tutorials/tutorial-create-data-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @abdale
* Microsoft Alias: **hamoodaleem**

**Comment by v-fearam** [comment]
Hi @pvath,


Sorry for the delay.

The "StaticPublicIPCountLimitReached" error message indicates that you have reached the limit of static public IP addresses allowed in your Azure subscription. This limit is a default limit set by Azure and cannot be increased for free accounts.


Use a [dynamic public IP address](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses). Instead of using a static public IP address, you can use a dynamic public IP address. A dynamic public IP address is assigned to your resource each time it starts, and can change each time the resource is restarted. You can modify the ARM template to use a dynamic public IP address instead of a static public IP address.


I will close the ticket, but I recommend leveraging the support options available in the Azure portal if you are still facing this issue.

**Comment by v-fearam** [comment]
#please-close
