### ISSUE TITLE
Viso linked not same as image

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/cloud-adoption-framework#1113]
The image on this page has details that are not in the linked Visio.  I.E. The management subscription details / example resources are not actually in the visio.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Please see the response in #1105.  I'm going to close this as a duplicate.

@jtracey93 -- is there any way you can save the Visio file with a specific page selected by default?  If so, having the "default" page in the Visio being the same as the shown image would help knock the confusion down for learners like this one and the one I linked to.  Seems the visio likes to default to one of your recent architecture page additions in the file instead of the hub spoke page.

#please-close

**Comment by Torxsmind** [comment]
I do not think this is a duplicate.   This is that the default tab in Visio
needs to be set. My complaint is that the tab for the reference is NOT in
the Visio at all.

**Comment by ckittel** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/671075/229237638-cbf9a3ed-edcf-4109-aa3a-1067f3632a9f.png">

**Comment by ckittel** [comment]
Just like #1105, the Visio Page is called "ALZ Hub & Spoke" -- that image matches the one published -- unless I'm missing something?  What's missing in that Visio Page from what is published?
