### ISSUE TITLE
Missing resource abbreviation for Private Endpoints

### ISSUE THREAD

**Issue by mcdonamw** [MicrosoftDocs/cloud-adoption-framework#1147]
What does MS suggest for private endpoint resources?  This is not mentioned anywhere in the framework list of service abbreviations.  I'm trying to use the Azure Naming Tool to control this but it does not allow customization of resource identifiers, only what MS defines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **ssumner**

**Comment by jamasten** [comment]
Hi @mcdonamw. Are you using the latest version of the Azure Naming Tool? The tool does allow you to modify the short names for all of the resource types included in the tool. Private endpoints are currently missing and we're working to fix this gap.

**Comment by mcdonamw** [comment]
Yes I am using the latest and I am aware that you can edit entries that already exist.  We have the option to add custom entries in other areas, why not the services?  It would be nice if I could add my own entry for private endpoints as I think the main issue here is MS themselves are missing private endpoints in their own abbreviation documentation.

**Comment by jamasten** [comment]
@mcdonamw I'll be fixing the resource naming documentation shortly after I update the Azure Naming Tool with the missing resources. If you want to manually add a resource yourself, you can export the resource types configuration, add an object with the all the properties, and import the configuration. However, we don't plan to add a UI capability to add resources since we plan to fix the issue in the near future.

**Comment by mcdonamw** [comment]
Ok thanks!  What happens if MS adds new resources in the future?  Are we to manually update these via that export/import function until you find time to add them yourself, or is this dynamically pulled from MS?  Is it based on their documentation or from somewhere else?

If dynamic, and MS even fails to update their documentation (as is the case for private endpoints today), wouldn't it be easier for us to manually add via the UI vs that export/import option?

Also, what is the github issues location for the Azure Naming Tool itself?  I thought this was it but now see this is documentation and I've posted a few issues incorrectly here.

**Comment by stephen-sumner** [comment]
@mcdonamw - Thank you for your feedback! I just looked and private endpoints must have been added to the list since you raised the issue. `pep` is the abbreviation example we give.

<img width="443" alt="image" src="https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/109609721/8bbd69d9-f7f4-45d5-80df-2d585f7b4b69">

**Comment by stephen-sumner** [comment]
@mcdonamw - Thanks so much for the feedback!
