### ISSUE TITLE
No access to "Data and AI Demo Megamap"

### ISSUE THREAD

**Issue by k-krupka** [MicrosoftDocs/cloud-adoption-framework#1294]
I am not sure if this is the case, but while reading the article series from top to bottom, i've encountered the link to demo broken / incorrect.

See here:
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/industry/retail/industry-priority-scenarios#see-intelligent-retail-hands-on-with-a-retail-industry-demo

I wanted to play around with the map, but got no access instead:

![image](https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/20299573/2fc93624-0ccd-4d77-b471-801ba2a46592)

Is this expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 902df803-acad-cc32-0018-4d83fd5039bf
* Version Independent ID: 902df803-acad-cc32-0018-4d83fd5039bf
* Content: [Industry priority scenarios in the retail industry - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/industry/retail/industry-priority-scenarios)
* Content Source: [docs/industry/retail/industry-priority-scenarios.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/industry/retail/industry-priority-scenarios.md)
* Service: **caf**
* Sub-service: **caf-scenario-retail**
* GitHub Login: @mpvenables
* Microsoft Alias: **jaalmond**

**Comment by ckittel** [comment]
The "Data & AI Dream Demo Hub" is supported through [dreamdemossupport@spektrasystems.com](mailto:dreamdemossupport@spektrasystems.com) and [dreamdemos@microsoft.com](mailto:dreamdemos@microsoft.com), not through the Cloud Adoption Framework for Azure content team.  We'll have to close the issue here, and request that you seek support from the team that can help you at those email addresses.

#please-close
