### ISSUE TITLE
Question: Platform MG hierarchy

### ISSUE THREAD

**Issue by pazdedav** [MicrosoftDocs/cloud-adoption-framework#378]
What is the benefit of separating Connectivity, Identity, and Management into separate MGs under the Platform MG? Is it expected that these platform subscriptions will need to scale out to more than one subscription per "area"? Wouldn't it be better to either assign required DINE policies on subscription level or have a simplified structure with one Platform MG and one subscription hosting all components for identity, management, and connectivity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38786a5-e931-e614-55a1-2980b8a28087
* Version Independent ID: a72b6f97-dd0f-252c-f6d9-f1c517aa9a2f
* Content: [Management group and subscription organization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization)
* Content Source: [docs/ready/enterprise-scale/management-group-and-subscription-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-group-and-subscription-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/357643/>357643</a>

**Comment by JanetCThomas** [comment]
@JefferyMitchell - could you please review this issue?

**Comment by krnese** [comment]
The benefit is that management group will be the container for the policyAssignment regardless of when the subscription is then added to the management group, and is consistent with what's enabled on the landing zones and enables the native platform autonomy vs coupling assignments to the subscriptions directly.

**Comment by pazdedav** [comment]
Thanks for your input @krnese . I understand the principle of MG-level policy assignments and its benefits. My question was specifically about the Platform MG, not about landing zones hosting workloads (and respective MG structure like corp, online, etc.). 

I am trying to understand, why is there a Platform MG with three nested MGs (Connectivity, Identity, Management), each sub-MG hosting separate subscriptions for this single purpose. This might appear as too complex, considering how many and what resource types these Platform subscriptions host. 

Is the main purpose to ensure autonomy for teams providing centralized services (like NetOps, IAM team) by allocating separate subscriptions for them or do you also anticipate a potential need to "scale out", e.g. have two "Connectivity subscriptions" due to a possibility to reach some limitation?

**Comment by krnese** [comment]
A couple of reasons: 
1) As a design principle, we have subscription democratization, hence we adhere to the principles on the platform - as well as on the landing zone side
2) There should not be an increased complexity due to what I explained earlier, where the policyassignment is paritioned on the management group regardless of when the subscription comes, to enable autonomy (ie., this structure does not require more efforts - it reduces the efforts with such decoupling)
3) It is clean and consistent for the all-up architecture vs doing something special for the platform side that is causing different approaches for policy lifecycle and operations in general regardless of type of subscription
4) It allows customers to scale on the platform side _if they decide to do so_ vs not being able to scale in a similar fashion, and cates for segregation of duties aligned with everything else in the all up architecture.

The gist of the above is; consistency, be loyal to design principles, and ensure autonomy being preventive and proactive for Azure as whole.

**Comment by pazdedav** [comment]
Ok, I understand it better now. Thanks for a comprehensive answer, @krnese :)
