### ISSUE TITLE
Postfix vs Prefix

### ISSUE THREAD

**Issue by v-wilock** [MicrosoftDocs/cloud-adoption-framework#53]
This page recommends prefixing resource type onto a resource's name, but the [linked architecture page](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming) page recommends postfixing.
Compare `profx-prod-rg` with `rg-profx-prod`. One or the other should be the accepted standard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fae12c42-b9f4-ae42-566f-35435f80f9c6
* Version Independent ID: 4d714a74-031d-c9f7-2fa0-6b69fc5f609a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by jlorich** [comment]
I am curious what the rational for switching from postfix to prefix was.  As we've been recommending postfix for a decade it'd be great to provide some understanding for "why pre" in the docs.

**Comment by jlorich** [comment]
In fact, I'm hard pressed to see why using a prefix is better.  When my resources are sorted in a group I prefer them to be organized logically.  Since the portal sorts alphabetically, keeping the "name" first makes a lot of sense.

For example:
- `openhack-demo-kv`
- `openhack-demo-cosdb`
- `openhack-demo-aks`

Would all get nicely sorted together in a big list, as they belong, but if I used resource first they'd wind up all over the place mixed in with other projects.

Certainly we can use resource groups to help organize things together, but many organizations do not allow free reign for creating resource groups and it can make sense to keep a few different things in one resource group.

**Comment by alexbuckgit** [comment]
We've revised the structure of our naming guidance, which now encourages readers to choose the order of the components in resource names based on their organizational needs, rather than stipulating a certain prefix. Thanks for the feedback!
