### ISSUE TITLE
Hungerian notation

### ISSUE THREAD

**Issue by sqlenders** [MicrosoftDocs/cloud-adoption-framework#590]
I get a deja vu when I see this. It reminds me of the Hungarian notation here : https://en.wikipedia.org/wiki/Hungarian_notation 
Also Microsoft naming convention disapprove this here : https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions
Issues I have : 
- are you naming databases like db1 , db2 ? or like db-sales ? Or Salesdb ? I have a database just called Sales pretty clear. 
- if you implement a region code and you are moving it to another region you have to rename it. 
An indentification is meant to be unique and should not change over time. 

I am refering to this page : https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

Just my two cents

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/486317/>486317</a>

**Comment by stephen-sumner** [comment]
@sqlenders - I know this has been a long time since you first report. Thank you for your input. Our apologies for not addressing your question years ago. We have recommended database naming examples on this page: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming#example-names-databases

sqldb-<project, app or service>-<environment> and if needed you can add a numbering system to the end to differentiate

**Comment by stephen-sumner** [comment]
#please-close
