### ISSUE TITLE
Confusing page

### ISSUE THREAD

**Issue by lunar87** [MicrosoftDocs/cloud-adoption-framework#639]
[Enter feedback here]
The title on this page is comparison of COMs, but previously in the overview COM was defined as 'A cloud operating model is the collection of processes and procedures that define how you want to operate technology in the cloud.'

But then saying on this page that COM is decentralized, centralized, enterprise or distributed doesn't make sense. I think a better title for the comparison would be "Operating model implementation comparison" because COM doesn't change, but how it is implemented does. 

Additionally I would add is the table is confusing. It states that 'Strategic priorities and motivations' and Portfolio Scope are the two driving factors, but then the table has 6 rows. I think the other 4 matter as well and should be pointed out and defined. 

Also make row 1 consistent, it should be "Strategic priorities and motivations", and not just strategic priorities. 
The explanation of this is also confusing, "Strategic priorities or motivations: Each operating model is capable of delivering the typical strategic motivations for cloud adoption. However, some operating models simplify realizing specific motivations." This now says the two are 'OR' vs. 'And' Also what does the statement, "some operating models simplify realizing specific motivations" supposed to mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb84d9b-3890-58cc-cc5c-547247b23a1a
* Version Independent ID: 025a2790-d3bd-e25e-1c4b-3b5e4bc46797
* Content: [Review and compare common cloud operating models - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/compare)
* Content Source: [docs/operating-model/compare.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/operating-model/compare.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
Hi @dineshspatelms

Sorry for the delay. 


The document has changed a lot since the issue was reported. 

[Here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/#how-is-a-cloud-operating-model-different) is the definition that you pointed out “A cloud operating model is the collection of processes and procedures that define how you want to operate technology in the cloud.”, but in the [same document](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/#define-your-operating-model) says “The next few articles share foundational terms and provide examples of common operating models.”. There are several cloud operating models, each one with a different set of processes and procedures. Decentralized, centralized, enterprise or distributed are different sets for different processes for different scenarios. 

In the [Priority or Scope Section](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/compare#priorities-or-scope) , the author try to focus in the **primary** two factors, then those two are explained in detail. 

[I created a PR](https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/4587) creating consistency on “Strategic priorities or motivations” references.

The Ticket will be closed when the PR gets merged.
