### ISSUE TITLE
Visio page duplication

### ISSUE THREAD

**Issue by evanriser** [MicrosoftDocs/cloud-adoption-framework#868]
The two pages in the linked Visio diagram showing the enterprise landing zone, are duplicates despite having different titles.
One is "Enterprise-scale VWAN" and the other "Enterprise-scale Hub & Spoke" however the same diagram is presented in both which is the hub and spoke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by Zimmergren** [comment]
Hey @evanriser , thank you for reporting this. There's been some updates to the Visio diagram since this was reported.

Azure Landing Zones (ALZ) does have two Connectivity subscription flavors. One is the hub-spoke (hub virtual network) and the other is virtual WAN (VWAN service as hub). In the Visio diagrams, there are subtle differences in the Connectivity subscription sections that cater for these two scenarios specifically. Typically, a customer chooses one or the other. 

In the Visio, these two diagrams are now named: 

- ALZ Hub & Spoke
- ALZ VWAN

#please-close
