### ISSUE TITLE
Mitigation for scenario two - will the policy denies the approval of private endpoint connections from a different subscription in same tenant?

### ISSUE THREAD

**Issue by rjosephp** [MicrosoftDocs/cloud-adoption-framework#873]
The policy definition provided for Mitigation for scenario two, isn't it checking only for the Subscription Id and not tenant id? If that is the case, will it deny the approval of PE connection from a different subscription in the same Tenant also? 

"if": {
    "allOf": [
        {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts/privateEndpointConnections"
        },
        {
            "field": "Microsoft.Storage/storageAccounts/privateEndpointConnections/privateLinkServiceConnectionState.status",
            "equals": "Approved"
        },
        {
            "anyOf": [
                {
                    "field": "Microsoft.Storage/storageAccounts/privateEndpointConnections/privateEndpoint.id",
                    "exists": false
                },
                {
                    "value": "[split(concat(field('Microsoft.Storage/storageAccounts/privateEndpointConnections/privateEndpoint.id'), '//'), '/')[2]]",
                    **_"notEquals": "[subscription().subscriptionId]"_**
                }
            ]
        }
    ]
},
"then": {
    "effect": "Deny"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49413641-0c1f-9862-9113-9b24f39b6dd9
* Version Independent ID: ed547d74-59ed-0f48-ba0d-825370d792a8
* Content: [Limit cross-tenant private endpoint connections in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections)
* Content Source: [docs/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @marvinbuss
* Microsoft Alias: **mabuss**

**Comment by marvinbuss** [comment]
Hi @rjosephp,
That is correct. It only checks for the subscription Id and not tenant Id, because there is no tenant ID property for a private endpoint. Therefore, we cannot check on a tenant id for mitigating the risk.
I hope this helps. Please let me know if you have more questions or close the issue. Thanks! 👍

**Comment by rjosephp** [comment]
@marvinbuss Thanks for the response and for confirming this. If that is the case, the header "Limit **cross-tenant** private endpoint connections in Azure" is confusing. This is actually limiting cross-subscription private endpoint connections, and that should be made clear in the article.

**Comment by hallihan** [comment]
@marvinbuss Can you follow up here, and close the issue if this is complete?

**Comment by marvinbuss** [comment]
> @marvinbuss Thanks for the response and for confirming this. If that is the case, the header "Limit **cross-tenant** private endpoint connections in Azure" is confusing. This is actually limiting cross-subscription private endpoint connections, and that should be made clear in the article.

The original intention is to limit cross-tenant private endpoints. Due to the fact that there is no tenant ID property available, we have to be more restrictive and limit deployments to the same subscription. This is also mentioned in the article quite clearly when describing what the policy does:
![image](https://user-images.githubusercontent.com/34542414/195867320-daa75e50-3f17-45c1-9ead-00588c0ad26c.png)

Do you have any other questions @rjosephp?
Otherwise, we can close this @hallihan.

**Comment by hallihan** [comment]
Closing since there were no additional comments. #please-close
