### ISSUE TITLE
Power BI File Fails to connect to Pricing API

### ISSUE THREAD

**Issue by adamswbrown** [MicrosoftDocs/cloud-adoption-framework#888]
The Linked Power BI template does not work, the included URL's within the BI template, fail (error 400)

Error: 
DataSource.Error: Web.Contents failed to get contents from 'https://prices.azure.com/api/retail/prices?currencyCode='GBP%E2%80%8B'&$filter=%0A(indexof(location,%20'%20')%20ne%20-1%20or%20location%20eq%20'Global'%20or%20location%20eq%20'')%20%0Aand%20indexof(serviceName,%20'Virtual%20Machines')%20ne%20-1%20%0Aand%20indexof(productName,%20'%20Series')%20ne%20-1%0Aand%20indexof(productName,%20'%20Dedicated')%20eq%20-1%0Aand%20priceType%20eq%20'Consumption'%20%0Aand%20indexof(skuName,%20'Spot')%20eq%20-1%20%0Aand%20indexof(meterName,'Expired')%20eq%20-1%20%0Aand%20indexof(meterName,'Low%20Priority')%20eq%20-1%20%0Aand%20indexof(meterName,%20'Promo')%20eq%20-1' (400): Bad Request

https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/strategy/azure-virtual-machine-cost-estimator.pbix

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42f8649e-4a66-2667-b4c7-88698cf5183f
* Version Independent ID: ce9e86a7-423d-7177-685d-ed9f426940b5
* Content: [Create a business case - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/strategy/cloud-migration-business-case)
* Content Source: [docs/strategy/cloud-migration-business-case.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/strategy/cloud-migration-business-case.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @WendyRing
* Microsoft Alias: **wering**

**Comment by BryanLa** [comment]
@adamswbrown - apologies for the delayed response and thanks very much for this contribution.

We're not able to repro the 400 error nor the ones reported since you opened this issue. I've also reported this to the author of the template in the event that it's been updated/resolved since then, or if these are known issues that have a workaround, or should be documented. We'll update this issue if/when we get updates from the author, and please also feel free to update with any additional repro info you might have or status updates..

#please-close
