### ISSUE TITLE
Abbreviation missing for newly added asset types like Origin Group

### ISSUE THREAD

**Issue by maheshmitkari** [MicrosoftDocs/cloud-adoption-framework#940]
Abbreviation are missing for many newly added asset types / services in this list. 
e.g. In Azure Front Door standard premium services, abbreviation is not provided for this new front door service, for front door classic it is mentioned at fd but in sample quick start ARM template it is referred as "afd", also for Microsoft.Cdn/Profiles/OriginGroups, Microsoft.Cdn/Profiles/OriginGroups/Origins, Microsoft.Cdn/Profiles and many other such newly added services the abbreviation is not covered in this document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@maheshmitkari - Sorry for the delay in response! Thank you for your input! We added an abbreviation for Cdn/Profiles and afdEndpoints a little bit ago. However, at the moment, I don't see a need to add abbreviations for the child resources (origin groups, origins). Since the afd profile is required for every command I'm aware of and in the portal the origin groups are housed withing the FrontDoor service, I'll leave the list with just profile and endpoint.

However, if it clarifies your operations and enhances your work, I encourage you to adopt an abbreviation scheme that fits your environments. "og" might be a good abbreviation for origin groups and one I've seen in our CLI documentation.

Thank you!
