### ISSUE TITLE
Resource type prefixes

### ISSUE THREAD

**Issue by verbedr** [MicrosoftDocs/cloud-adoption-framework#999]
Please stop suggesting resource type prefixes in names.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **ssumner**

**Comment by Zimmergren** [comment]
Thank you for the comment, @verbedr .
The resource naming guidance is constantly evolving, and additional guidance may have been introduced since this ticket was opened. However, you can always opt-out of putting a prefix, and still follow the rest of the naming standard, which includes workload/app names.

**Comment by verbedr** [comment]
Hi,
Thank you for following this up. I still think the suggestion to use resource type in the name (and the use of a sequence) should be scaled down a bit. Now it seems to be strongly advice. While a sequence is sometimes not used.  Also in the sections about limits, especially about length limits it could there be suggested that as the scope of a resource is mostly within it's type the resource type prefix/postfix could be optional.

Anyway, at the time of opening this ticket, I was probably frustrated during an internal discussion. I want to thank you again for taking the time to address this. And I do understand that you closed it, as this topic is under continuous change and is very subjective.

Kr
Dries

**Comment by Zimmergren** [comment]
Thank you for elaborating, Dries. 
I've set up an internal discussion with relevant teams to hear what the discussions yield. We take all feedback into account, and your opinion matters! Thanks again!

**Comment by Frankkkkk** [comment]
Hi @Zimmergren , I agree with Dries too.
Unless I'm mistaken, this resource prefix addition comes when the Azure portal didn't have a "filter by resource" mode. Thus it was seen as a "good enough" idea.

Nowadays, tbh, this seems redundant. Moreover, it's not global as some resource types don't have a recommended naming by Microsoft. Furthermore, by adding the ressource type suffix, even if may only be 3/4 characters (`-pep`, `-sa`, ...), it takes valuable naming characters and the "real" name of some resources is then shortened.

My points:
- no real usage (filter by type on the azure portal, creation by automated ways)
- no unification or addition of exceptions due to naming limitations.

Anyways, my 2cents, but thanks for taking them into consideration :-)

Cheers

**Comment by Zimmergren** [comment]
@Frankkkkk, thank you for submitting your thoughts - I'll add these notes to the discussion board for the teams to evaluate.
